# This patches the hermes2 Deployment containers to utilize the 
# image built for a Rubin custom Hermes daemon with Kafka support

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-rucio-daemons-hermes
spec:
  template:
    spec:
      containers:
        - name: rucio-daemons
          image: "ghcr.io/lsst-dm/rucio-daemons-hermesk:38.5.5"
          volumeMounts:
            - name: ca-volume
              mountPath: /etc/grid-security/certificates
      volumes:
        - name: ca-volume
          secret:
            $patch: delete
          persistentVolumeClaim:
            claimName: grid-certificates-pvc
