apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: usdf-rucio-daemons-renew-fts-proxy-on-helm-install
spec:
  ttlSecondsAfterFinished: 60
