# This patches the hermes2 Deployment containers to utilize the 
# image built for a Rubin custom Hermes daemon with Kafka support

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-hermes
spec:
  template:
    spec:
      initContainers:
      - name: grid-certs
        image: docker.io/bjwhitefnal/fetch-crl-cron:latest
        volumeMounts:
        - name: ca-volume
          mountPath: /out/
      containers:
        - name: rucio-daemons
          image: "ghcr.io/lsst-dm/rucio-daemons-hermesk:35.6.0.1"
          volumeMounts:
            - name: proxy-volume
              mountPath: /opt/proxy
            - name: ca-volume
              mountPath: /etc/grid-security/certificates
      volumes:
        - name: proxy-volume
          secret:
            secretName: usdf-rucio-x509up
        - name: ca-volume
          secret:
            $patch: delete
          persistentVolumeClaim:
            claimName: grid-certificates-pvc
