---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: usdf-rucio-16b-pooler-rw
  namespace: rucio-db-16b
spec:
  cluster:
    # the name here is not the cluster name, but the name of DB service that the pooler will control.
    # CNPG-operator automatcally added number to the name and starting from 1. It will not reuse 
    # the number if we redeploy a new DB. example of the name is usdf-rucio-1, usdf-rucio-2, ...
    name: usdf-rucio-16b
  instances: 3
  type: rw

  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "500"
      default_pool_size: "450"
      log_connections: "1"
      log_disconnections: "1"
      idle_transaction_timeout: "0"
      server_idle_timeout: "0"
      tcp_keepalive: "1"
      tcp_keepcnt: "1"
      tcp_keepidle: "1"
      tcp_keepintvl: "1"
      tcp_user_timeout: "21600"

  template:
    metadata:
      labels:
        app: pooler
      annotations:
        prometheus.io/scrape: 'true'
    
    spec:
    
      containers:
      - name: pgbouncer
        #image: my-pgbouncer:latest
        resources:
          requests:
            cpu: "0.1"
            memory: 100Mi
          limits:
            cpu: "0.5"
            memory: 500Mi

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pooler
            topologyKey: "kubernetes.io/hostname"
---
