apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-rucio
  namespace: rucio-db-16b
spec:
  backup:
    retentionPolicy: "15d"
    barmanObjectStore:
      destinationPath: s3://rubin-rucio
      endpointURL: https://s3dfrgw.slac.stanford.edu:443
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds
          key: ACCESS_SECRET_KEY
  instances: 3
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: rucio
      owner: rubin
      secret:
        name: usdf-rucio-creds
  
  imageName:  ghcr.io/cloudnative-pg/postgresql:16.6
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true' 

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    parameters:
      log_disconnections: "on"
      log_duration: "on"
      log_min_duration_statement: 250ms
      log_statement: all
      log_temp_files: "1"
      max_connections: "250"
      shared_buffers: 8GB
      work_mem: 16MB
      maintenance_work_mem: 512MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  resources:
    requests:
      memory: 8Gi
      cpu: 8
    limits:
      memory: 32Gi
      cpu: 16 

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 1000Gi
