apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: rucio-kafka
  namespace: kafka
spec:
  kafka:
    version: 3.9.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        #authentication:
        #  type: scram-sha-512
        configuration:
          bootstrap:
            loadBalancerIP: 134.79.23.202
            annotations:
              metallb.universe.tf/address-pool: sdf-dmz
          brokers:
            - broker: 0
              annotations:
                metallb.universe.tf/address-pool: sdf-dmz
            - broker: 1
              annotations:
                metallb.universe.tf/address-pool: sdf-dmz
            - broker: 2
              annotations:
                metallb.universe.tf/address-pool: sdf-dmz
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.9"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: wekafs--sdf-k8s01
        size: 5Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: wekafs--sdf-k8s01
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: 
      watchedNamespace: kafka
    userOperator: {}
