---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: slac-test-disk-dp1test01
  labels:
    strimzi.io/cluster: rucio-kafka
spec:
  topicName: SLAC_TEST_DISK-dp1test01
  partitions: 3
  replicas: 2
  config:
    retention.ms: 21600000
    segment.bytes: 268435456
---
