apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: rucio-kafka-controller-pool
  labels:
    strimzi.io/cluster: rucio-kafka
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      kraftMetadata: shared
      class: wekafs--sdf-k8s01
      size: 5Gi
      deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: rucio-kafka-broker-pool
  labels:
    strimzi.io/cluster: rucio-kafka
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      kraftMetadata: shared
      class: wekafs--sdf-k8s01
      size: 5Gi
      deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: rucio-kafka
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          allocateLoadBalancerNodePorts: false
          bootstrap:
            loadBalancerIP: 134.79.23.189
            annotations:
              metallb.io/address-pool: sdf-dmz
          brokers:
            - broker: 0
              annotations:
                metallb.io/address-pool: sdf-dmz
            - broker: 1
              annotations:
                metallb.io/address-pool: sdf-dmz
            - broker: 2
              annotations:
                metallb.io/address-pool: sdf-dmz
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.9"
      auto.create.topics.enable: "false"
  entityOperator:
    topicOperator: 
      watchedNamespace: kafka
    userOperator: {}
