
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-rucio
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: lsstdb1
      owner: rubin
      secret:
        name: usdf-butler-butler-creds
  
  imageName: ghcr.io/cloudnative-pg/postgresql:14.4-7
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true'

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    parameters:
      shared_buffers: 16GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
#      ldap:
#        scheme: ldaps
#        server: 'ldap-unix.slac.stanford.edu'
#        # tls: true
#        port: 636
#        bindAsAuth:
#          prefix: 'uid='
#          suffix: ',ou=Accounts,dc=slac,dc=stanford,dc=edu'


  resources:
    requests:
      memory: 64Gi
      cpu: 16
    limits:
      memory: 128Gi
      cpu: 32

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 1000Gi


