---
# Source: eck-elasticsearch/templates/elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-eck-elasticsearch
  labels:
    helm.sh/chart: eck-elasticsearch-0.8.0
    app.kubernetes.io/name: eck-elasticsearch
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/managed-by: Helm
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
  updateStrategy:
    changeBudget:
      maxSurge: 3
      maxUnavailable: 1
  version: 8.11.0
  volumeClaimDeletePolicy:
    DeleteOnScaledownOnly
  nodeSets:
    
    - config:
        node.roles:
        - master
        node.store.allow_mmap: false
      count: 3
      name: master
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                cpu: 2
                memory: 5Gi
              requests:
                cpu: 1
                memory: 3Gi
    - config:
        node.roles:
        - data
        - ingest
        - transform
        node.store.allow_mmap: false
      count: 3
      name: worker
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                cpu: 3
                memory: 9Gi
              requests:
                cpu: 1
                memory: 5Gi
