apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: rucio-dev-db-backup
  namespace: rucio-db-dev
spec:
  immediate: true
  schedule: "0 0 1 * * *"
  backupOwnerReference: self
  cluster:
    name: rucio-db
