apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: rucio-db-ss
  namespace: rucio-db-dev
spec:
  cluster:
    name: rucio-db
  instances: 6
  pgbouncer:
    parameters:
      default_pool_size: "1000"
      idle_transaction_timeout: "300"
      log_connections: "1"
      log_disconnections: "1"
      max_client_conn: "3000"
      server_idle_timeout: "60"
      tcp_keepalive: "1"
      tcp_keepcnt: "1"
      tcp_keepidle: "1"
      tcp_keepintvl: "1"
      tcp_user_timeout: "5000"
    paused: false
    poolMode: session
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: pooler
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pooler
            topologyKey: kubernetes.io/hostname
      containers:
      - name: pgbouncer
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
          requests:
            cpu: "1"
            memory: 500Mi
  type: rw

---

apiVersion: v1
kind: Service
metadata:
  name: rucio-db-ss
  namespace: rucio-db-dev
spec:
  type: ClusterIP
  ipFamilies:
  - IPv4
  ports:
  - name: pgbouncer
    port: 5432
  selector:
    app: pooler
    cnpg.io/poolerName: rucio-db-ss
