namespace: rucio-db-16

resources:
- ns.yaml
- cnpg-rucio-pooler.yaml
#- cnpg-rucio-pooler-lb-svc.yaml
- cnpg-rucio-database.yaml
- backup.yaml

secretGenerator:
# database
- name: usdf-rucio-dev-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password
- name: s3-creds
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/client-id
  - ACCESS_SECRET_KEY=etc/.secrets/client-secret
